use_frameworks!

target 'ASImagePicker_Example' do
  pod 'ASImagePicker', :path => '../'

  target 'ASImagePicker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0', :inhibit_warnings => true
  pod 'Nimble', '~> 5.1.1', :inhibit_warnings => true
  end
end
